package com.flinkuse.cases.cqcal.constant;

/**
 * 任务常量类包含sql
 * @author learn
 * @date 2023/5/17 13:50
 */
public class CqFinal {

    public static String categoryPro = "select category_pro_id,category_pro_name,category_pro_unit,category_pro_group,category_pro_index FROM scps_mysql_ods.t_category_pro final WHERE data_flag > 0";

    public static String skuMsg = "SELECT\n\tsku.ten_partsku_id as ten_partsku_id,\n\tsku.ten_partsku_code as ten_partsku_code,\n\tsku.ten_partsku_name as ten_partsku_name,\n\tsku.ten_partsku_unicode as ten_partsku_unicode,\n\tsku.ten_partsku_type as ten_partsku_type,\n\tsku.ten_partsku_down_switch as ten_partsku_down_switch,\n\tsku.ten_partsku_external_code as ten_partsku_external_code,\n\tsku.ten_partsku_feature as ten_partsku_feature,\n\tsku.ten_partsku_order_url as ten_partsku_order_url,\n\tsku.ten_partsku_course_url as ten_partsku_course_url,\n\tsku.tenant_id as tenant_id,\n\tsku.ten_brand_id as ten_brand_id,\n\tsku.ten_category_id as ten_category_id,\n\tsku.ten_part_id as ten_part_id,\n\tsku.ten_partsku_desc as ten_partsku_desc,\n\tsku.ten_partsku_desc_img as ten_partsku_desc_img,\n\tsku.category_id as category_id,\n\tsku.create_by as create_by,\n\tsku.create_time as create_time,\n\tsku.update_by as update_by,\n\tsku.update_time as update_time,\n\tskuval.ten_partsku_value as ten_partsku_value,\n\ttc.partsku_exchange_code as partsku_exchange_code\nFROM\n\t(\n\tselect\n\t\tten_partsku_id,\n\t\tten_partsku_code,\n\t\tten_partsku_name,\n\t\tten_partsku_unicode,\n\t\tten_partsku_type,\n\t\tten_partsku_down_switch,\n\t\tten_partsku_external_code,\n\t\tten_partsku_feature,\n\t\tten_partsku_order_url,\n\t\tten_partsku_course_url,\n\t\ttenant_id,\n\t\tten_brand_id,\n\t\tten_category_id,\n\t\tten_part_id,\n\t\tten_partsku_desc,\n\t\tten_partsku_desc_img,\n\t\tcategory_id,\n\t\tten_data_type,\n\t\tcreate_by,\n\t\tcreate_time,\n\t\tupdate_by,\n\t\tupdate_time\n\tFROM\n\t\tscps_mysql_ods.t_tenant_partsku final\n\tWHERE ${ten_partsku_id}\n\t\tdata_flag > 0) sku\nGLOBAL\nLEFT JOIN (\n\tselect\n\t\tten_partsku_id,\n\t\tarrayStringConcat(groupArray(concat(toString(category_pro_id),\n\t\t':',\n\t\tten_partsku_value)),\n\t\t',') as ten_partsku_value\n\tFROM\n\t\tscps_mysql_ods.t_tenant_partsku_value final\n\twhere ${ten_partsku_id}\n\t\tdata_flag > 0\n\tGROUP BY\n\t\tten_partsku_id) as skuval \n\t\t\ton\n\tsku.ten_partsku_id = skuval.ten_partsku_id\nGLOBAL\nLEFT JOIN (\nSELECT\n\tten_partsku_id,\n\tconcat('[',\n\tarrayStringConcat(groupArray(concat('{\"partsku_exchange_code\":\"',\n\treplaceAll(partsku_exchange_code,'\"','\\\\\\\\\"'),\n\t'\",\"partsku_exchange_fmt_code\":\"',\n\tpartsku_exchange_fmt_code,\n\t'\",\"partsku_exchange_type\":\"',\n\tpartsku_exchange_type,\n\t'\"}')),\n\t','),\n\t']') partsku_exchange_code\nFROM\n\tscps_mysql_ods.t_tenant_partsku_exchange final\nwhere\n\t${ten_partsku_id}\n\tdata_flag > 0\nGROUP BY\n\tten_partsku_id) as tc\n\tON \n\tsku.ten_partsku_id=tc.ten_partsku_id";

    public static String skuImg = "select\n\ta.ten_partsku_id,\n\ta.ten_partsku_image_index,\n\tb.ten_partsku_image_name,\n\tb.ten_partsku_image_url\nfrom\n\t(\n\tselect\n\t\tten_partsku_image_id,\n\t\tten_partsku_image_index,\n\t\tten_partsku_id\n\tfrom\n\t\tscps_mysql_ods.t_tenant_partsku_image_rel final\n\twhere ${ten_partsku_id}\n\t\tdata_flag > 0) a\nGLOBAL\nJOIN (\n\tSELECT\n\t\tten_partsku_image_id,\n\t\tten_partsku_image_name,\n\t\tten_partsku_image_url\n\tfrom\n\t\tscps_mysql_ods.t_tenant_partsku_image final\n\tWHERE\n\t\tdata_flag > 0\n) b on\n\ta.ten_partsku_image_id = b.ten_partsku_image_id";

    // 车型到产品的适配 带有 备注 标准码属性
    // public static String skuAdapter = "SELECT\n\trel.tenant_id tenant_id,\n\trel.ten_brand_id ten_brand_id,\n\trel.ten_category_id ten_category_id,\n\trel.category_id category_id,\n\trel.std_tree_id std_tree_id,\n\trel.std_partsku_id std_partsku_id,\n\trel.oem_partsku_id oem_partsku_id,\n\trel.ten_partsku_id ten_partsku_id,\n\trel.cm_id cm_id,\n\trel.oem_partsku_fmt_code oem_partsku_fmt_code,\n\trel.ten_cm_comment ten_cm_comment,\n\tcom.oem_carmodel_comment_desc oem_carmodel_comment_desc,\n\tcom.rm_cm rm_cm,\n\tstdval.std_partsku_value std_partsku_value\nFROM\n\t(\n\tSELECT\n\t\ttenant_id,\n\t\tten_brand_id,\n\t\tten_category_id,\n\t\tcategory_id,\n\t\tstd_tree_id,\n\t\tstd_partsku_id,\n\t\toem_partsku_id,\n\t\tten_partsku_id,\n\t\tcm_id,\n\t\toem_partsku_fmt_code,\n\t\tten_cm_comment\n\tfrom\n\t\tscps_mysql_ods.t_tenant_cm_rel final\n\tWHERE ${ten_cm_rel_id}\n\t\tdata_flag > 0) rel\nGLOBAL\nLEFT JOIN \n(\n\tSELECT\n\t\ta.cm_id cm_id,\n\t\ta.oem_partsku_id oem_partsku_id,\n\t\tb.oem_carmodel_comment_desc oem_carmodel_comment_desc,\n\t\tc.rm_cm rm_cm\n\tFROM\n\t\t(\n\t\tSELECT\n\t\t\tcm_id,\n\t\t\toem_partsku_id,\n\t\t\toem_carmodel_remark_id\n\t\tFROM\n\t\t\tscps_mysql_ods.t_oem_carmodel_rel final\n\t\tWHERE ${oemcm}\n\t\t\tdata_flag > 0\n\t\t\tand oem_carmodel_remark_id != 0) a \nGLOBAL\n\tJOIN \n(\n\t\tSELECT\n\t\t\toem_carmodel_remark_id,\n\t\t\toem_carmodel_comment_desc\n\t\tFROM\n\t\t\tscps_mysql_ods.t_oem_carmodel_comment final\n\t\tWHERE\n\t\t\tdata_flag > 0) b ON\n\t\ta.oem_carmodel_remark_id = b.oem_carmodel_remark_id\nGLOBAL\n\tJOIN \n(\n\t\tSELECT\n\t\t\toem_carmodel_remark_id,\n\t\t\tarrayStringConcat(groupArray(CONCAT(toString(cm_pro_id),\n\t\t\t':',\n\t\t\tcm_pro_name,\n\t\t\t':',\n\t\t\tcm_pro_column,\n\t\t\t':',\n\t\t\toem_carmodel_extend_val)),\n\t\t\t';') as rm_cm\n\t\tFROM\n\t\t\tscps_mysql_ods.t_oem_carmodel_extend final\n\t\tWHERE\n\t\t\tdata_flag > 0\n\t\tGROUP BY\n\t\t\toem_carmodel_remark_id\n) c ON\n\t\ta.oem_carmodel_remark_id = c.oem_carmodel_remark_id) as com ON \n\trel.cm_id = com.cm_id\n\tand rel.oem_partsku_id = com.oem_partsku_id\nGLOBAL\nLEFT JOIN (\n\tselect\n\t\tstd_partsku_id,\n\t\tarrayStringConcat(groupArray(concat(toString(category_pro_id),\n\t\t':',\n\t\tstd_partsku_value)),\n\t\t',') as std_partsku_value\n\tFROM\n\t\t(select std_partsku_id,category_pro_id,std_partsku_value FROM scps_mysql_ods.t_standard_partsku_value final where ${std_partsku_id} data_flag > 0)\n\tGROUP BY\n\t\tstd_partsku_id) as stdval \n\t\t\ton\n\trel.std_partsku_id = stdval.std_partsku_id;";
    // 车型到产品的适配 带有 备注 无标准码属性
    public static String skuAdapter = "SELECT\n\trel.ten_cm_rel_id ten_cm_rel_id,\n\trel.tenant_id tenant_id,\n\trel.ten_brand_id ten_brand_id,\n\trel.ten_category_id ten_category_id,\n\trel.category_id category_id,\n\trel.std_tree_id std_tree_id,\n\trel.std_partsku_id std_partsku_id,\n\trel.oem_partsku_id oem_partsku_id,\n\trel.ten_partsku_id ten_partsku_id,\n\trel.cm_id cm_id,\n\trel.oem_partsku_fmt_code oem_partsku_fmt_code,\n\trel.ten_cm_rel_flag ten_cm_rel_flag,\n\trel.ten_cm_comment ten_cm_comment,\n\trel.ten_data_type ten_data_type,\n\trel.create_by create_by,\n\trel.create_time create_time,\n\tcom.oem_carmodel_comment_desc remark_comment,\n\tcom.rm_cm remark_extend\nFROM\n\t(\n\tSELECT\n\t\tten_cm_rel_id,\n\t\ttenant_id,\n\t\tten_brand_id,\n\t\tten_category_id,\n\t\tcategory_id,\n\t\tstd_tree_id,\n\t\tstd_partsku_id,\n\t\toem_partsku_id,\n\t\tten_partsku_id,\n\t\tcm_id,\n\t\toem_partsku_fmt_code,\n\t\tten_cm_rel_flag,\n\t\tten_cm_comment,\n\t\tten_data_type,\n\t\tcreate_by,\n\t\tcreate_time\n\tfrom\n\t\tscps_mysql_ods.t_tenant_cm_rel final\n\tWHERE ${ten_cm_rel_id}\n\t\tdata_flag > 0) rel\nGLOBAL\nLEFT JOIN \n(\n\tSELECT\n\t\ta.cm_id cm_id,\n\t\ta.oem_partsku_id oem_partsku_id,\n\t\ta.std_tree_id as std_tree_id,\n\t\tb.oem_carmodel_comment_desc oem_carmodel_comment_desc,\n\t\tc.rm_cm rm_cm\n\tFROM\n\t\t(\n\t\tSELECT\n\t\t\tcm_id,\n\t\t\toem_partsku_id,\n\t\t\tstd_tree_id,\n\t\t\toem_carmodel_remark_id\n\t\tFROM\n\t\t\tscps_mysql_ods.t_oem_carmodel_rel final\n\t\tWHERE \n\t\t\tdata_flag > 0\n\t\t\tand oem_carmodel_remark_id != 0) a \nGLOBAL\n\tJOIN \n(\n\t\tSELECT\n\t\t\toem_carmodel_remark_id,\n\t\t\toem_carmodel_comment_desc\n\t\tFROM\n\t\t\tscps_mysql_ods.t_oem_carmodel_comment final\n\t\tWHERE\n\t\t\tdata_flag > 0) b ON\n\t\ta.oem_carmodel_remark_id = b.oem_carmodel_remark_id\nGLOBAL\n\tJOIN \n(\n\t\tSELECT\n\t\t\toem_carmodel_remark_id,\n\t\t\tCONCAT('[',arrayStringConcat(groupArray(CONCAT('{\"cm_pro_id\":\"',toString(cm_pro_id),\n\t\t\t'\",\"cm_pro_name\":\"',cm_pro_name,\n\t\t\t'\",\"cm_pro_column\":\"',cm_pro_column,\n\t\t\t'\",\"oem_carmodel_extend_val\":\"',oem_carmodel_extend_val,'\"}')),','),']') as rm_cm\n\t\tFROM\n\t\t\tscps_mysql_ods.t_oem_carmodel_extend final\n\t\tWHERE\n\t\t\tdata_flag > 0\n\t\tGROUP BY\n\t\t\toem_carmodel_remark_id\n) c ON\n\t\ta.oem_carmodel_remark_id = c.oem_carmodel_remark_id) as com ON \n\trel.cm_id = com.cm_id\n\tand rel.oem_partsku_id = com.oem_partsku_id\n\tand rel.std_tree_id = com.std_tree_id";

    public static String stdMsg = "select std.std_partsku_id,\n\tstd.std_partsku_code,\n\tstd.std_tree_id,\n\tstd.std_partsku_desc,\n\tstd.std_partsku_desc_img,\n\tstd.std_partsku_status,\n\tstd.create_origin,\n\tstd.create_origin_id,\n\tstd.create_type,\n\tstd.create_by,\n\tstd.create_time,\n\tstd.update_by,\n\tstd.update_time,\n\tval.std_partsku_value\nFROM \n(SELECT\n\tstd_partsku_id,\n\tstd_partsku_code,\n\tstd_tree_id,\n\tstd_partsku_desc,\n\tstd_partsku_desc_img,\n\tstd_partsku_status,\n\tcreate_origin,\n\tcreate_origin_id,\n\tcreate_type,\n\tcreate_by,\n\tcreate_time,\n\tupdate_by,\n\tupdate_time\nFROM\n\tscps_mysql_ods.t_standard_partsku final\nWHERE ${std_partsku_id}\n\tdata_flag > 0) std\nGLOBAL\nLEFT JOIN (\n\tselect\n\t\tstd_partsku_id,\n\t\tarrayStringConcat(groupArray(concat(toString(category_pro_id),\n\t\t':',\n\t\tstd_partsku_value)),\n\t\t',') as std_partsku_value\n\tFROM\n\t\tscps_mysql_ods.t_standard_partsku_value final\n\twhere ${std_partsku_id}\n\t\tdata_flag > 0\n\tGROUP BY\n\t\tstd_partsku_id) as val \n\t\t\ton\n\tstd.std_partsku_id = val.std_partsku_id";

    public static String stdImg = "select\n\ta.std_partsku_id,\n\ta.std_partsku_image_index,\n\ta.std_partsku_image_type,\n\ta.category_pro_id,\n\tb.std_tree_id,\n\tb.std_partsku_image_url\nfrom\n\t(\n\tselect\n\t\tstd_partsku_id,\n\t\tstd_partsku_image_index,\n\t\tstd_partsku_image_id,\n\t\tstd_partsku_image_type,\n\t\tcategory_pro_id\n\tfrom\n\t\tscps_mysql_ods.t_standard_partsku_image_rel final\n\twhere ${std_partsku_id}\n\t\tdata_flag > 0) a\nGLOBAL\nJOIN (\n\tSELECT\n\t\tstd_partsku_image_id,\n\t\tstd_tree_id,\n\t\tstd_partsku_image_url\n\tfrom\n\t\tscps_mysql_ods.t_standard_partsku_image final\n\tWHERE\n\t\tdata_flag > 0\n) b on\n\ta.std_partsku_image_id = b.std_partsku_image_id";

    public static String insMsg = "select \n\tins.indus_partsku_id indus_partsku_id,\n\tins.indus_partsku_desc indus_partsku_desc,\n\tins.indus_partsku_desc_img indus_partsku_desc_img,\n\tins.indus_partsku_status indus_partsku_status,\n\tins.category_id category_id,\n\tins.indus_brand_id indus_brand_id,\n\tins.indus_category_id indus_category_id,\n\tins.create_origin create_origin,\n\tins.create_origin_id create_origin_id,\n\tins.create_type create_type,\n\tins.create_by create_by,\n\tins.create_time create_time,\n\tins.update_by update_by,\n\tins.update_time update_time,\n\tval.indus_partsku_value indus_partsku_value,\n\ttc.indus_partsku_code indus_partsku_code\nFROM \n(select\n\tindus_partsku_id,\n\tindus_partsku_desc,\n\tindus_partsku_desc_img,\n\tindus_partsku_status,\n\tcategory_id,\n\tindus_brand_id,\n\tindus_category_id,\n\tcreate_origin,\n\tcreate_origin_id,\n\tcreate_type,\n\tcreate_by,\n\tcreate_time,\n\tupdate_by,\n\tupdate_time\nFROM\n\tscps_mysql_ods.t_industry_partsku final\nwhere ${indus_partsku_id}\n\tdata_flag > 0) ins\nGLOBAL\nLEFT JOIN (\n\tselect\n\t\tindus_partsku_id,\n\t\tarrayStringConcat(groupArray(concat(toString(category_pro_id),\n\t\t':',\n\t\tindus_partsku_value)),\n\t\t',') as indus_partsku_value\n\tFROM\n\t\tscps_mysql_ods.t_industry_partsku_value final\n\twhere ${indus_partsku_id}\n\t\tdata_flag > 0\n\tGROUP BY\n\t\tindus_partsku_id) as val \n\t\t\ton\n\tins.indus_partsku_id = val.indus_partsku_id\nGLOBAL\nLEFT JOIN\n(SELECT\n\tindus_partsku_id,\n\tconcat('[',arrayStringConcat(groupArray(concat('{\"indus_partsku_code\":\"',replaceAll(indus_partsku_code,'\"','\\\\\"'),'\",\"indus_partsku_fmt_code\":\"',indus_partsku_fmt_code,'\"}')),','),']') indus_partsku_code\nFROM\n\tscps_mysql_ods.t_industry_partsku_code final\nwhere ${indus_partsku_id}\n\tdata_flag > 0\nGROUP BY\n\tindus_partsku_id) as tc\n\tON \n\tins.indus_partsku_id = tc.indus_partsku_id";

    public static String insImg = "select\n\ta.indus_partsku_id,\n\ta.indus_partsku_image_rel_index,\n\ta.indus_partsku_image_id,\n\ta.indus_partsku_image_type,\n\ta.category_pro_id,\n\tb.indus_partsku_image_url\nfrom\n\t(\n\tselect\n\t\tindus_partsku_id,\n\t\tindus_partsku_image_rel_index,\n\t\tindus_partsku_image_id,\n\t\tindus_partsku_image_type,\n\t\tcategory_pro_id\n\tfrom\n\t\tscps_mysql_ods.t_industry_partsku_image_rel final\n\twhere ${indus_partsku_id}\n\t\tdata_flag > 0) a\nGLOBAL\nJOIN (\n\tSELECT\n\t\tindus_partsku_image_id,\n\t\tindus_partsku_image_url\n\tfrom\n\t\tscps_mysql_ods.t_industry_partsku_image final\n\tWHERE\n\t\tdata_flag > 0\n) b on\n\ta.indus_partsku_image_id = b.indus_partsku_image_id";

    public static String fmsMsg = "select \n\tfms.fms_partsku_id fms_partsku_id,\n\tfms.fms_partsku_desc fms_partsku_desc,\n\tfms.fms_partsku_desc_img fms_partsku_desc_img,\n\tfms.fms_partsku_status fms_partsku_status,\n\tfms.category_id category_id,\n\tfms.fms_brand_id fms_brand_id,\n\tfms.fms_category_id fms_category_id,\n\tfms.create_origin create_origin,\n\tfms.create_origin_id create_origin_id,\n\tfms.create_type create_type,\n\tfms.create_by create_by,\n\tfms.create_time create_time,\n\tfms.update_by update_by,\n\tfms.update_time update_time,\n\tval.fms_partsku_value fms_partsku_value,\n\ttc.fms_partsku_code fms_partsku_code\nFROM \n(select\n\tfms_partsku_id,\n\tfms_partsku_desc,\n\tfms_partsku_desc_img,\n\tfms_partsku_status,\n\tcategory_id,\n\tfms_brand_id,\n\tfms_category_id,\n\tcreate_origin,\n\tcreate_origin_id,\n\tcreate_type,\n\tcreate_by,\n\tcreate_time,\n\tupdate_by,\n\tupdate_time\nFROM\n\tscps_mysql_ods.t_famous_partsku final\nWHERE ${fms_partsku_id}\n\tdata_flag > 0) fms\nGLOBAL\nLEFT JOIN (\n\tselect\n\t\tfms_partsku_id,\n\t\tarrayStringConcat(groupArray(concat(toString(category_pro_id),\n\t\t':',\n\t\tfms_partsku_value)),\n\t\t',') as fms_partsku_value\n\tFROM\n\t\tscps_mysql_ods.t_famous_partsku_value final\n\twhere ${fms_partsku_id}\n\t\tdata_flag > 0\n\tGROUP BY\n\t\tfms_partsku_id) as val \n\t\t\ton\n\tfms.fms_partsku_id = val.fms_partsku_id\nGLOBAL\nLEFT JOIN (\nselect\n\tfms_partsku_id,\n\tconcat('[',arrayStringConcat(groupArray(concat('{\"fms_partsku_code\":\"',replaceAll(fms_partsku_code,'\"','\\\\\"'),'\",\"fms_partsku_fmt_code\":\"',fms_partsku_fmt_code,'\"}')),','),']') fms_partsku_code\nFROM\n\tscps_mysql_ods.t_famous_partsku_code final\nwhere ${fms_partsku_id}\n\tdata_flag > 0\nGROUP BY\n\tfms_partsku_id) as tc \n\tON \n\tfms.fms_partsku_id = tc.fms_partsku_id";

    public static String fmsImg = "select\n\ta.fms_partsku_id,\n\ta.fms_partsku_image_rel_index,\n\ta.fms_partsku_image_id,\n\ta.fms_partsku_image_type,\n\ta.category_pro_id,\n\tb.fms_partsku_image_url\nfrom\n\t(\n\tselect\n\t\tfms_partsku_id,\n\t\tfms_partsku_image_rel_index,\n\t\tfms_partsku_image_id,\n\t\tfms_partsku_image_type,\n\t\tcategory_pro_id\n\tfrom\n\t\tscps_mysql_ods.t_famous_partsku_image_rel final\n\twhere ${fms_partsku_id}\n\t\tdata_flag > 0) a\nGLOBAL\nJOIN (\n\tSELECT\n\t\tfms_partsku_image_id,\n\t\tfms_partsku_image_url\n\tfrom\n\t\tscps_mysql_ods.t_famous_partsku_image final\n\tWHERE\n\t\tdata_flag > 0\n) b on\n\ta.fms_partsku_image_id = b.fms_partsku_image_id";

    public static String oemMsg = "SELECT \n\toem.oem_partsku_id oem_partsku_id,\n\toem.carmodel_brand_id carmodel_brand_id,\n\toem.std_tree_id std_tree_id,\n\toem.oem_partsku_desc oem_partsku_desc,\n\toem.oem_partsku_desc_img oem_partsku_desc_img,\n\toem.oem_partsku_status oem_partsku_status,\n\toem.create_origin create_origin,\n\toem.create_origin_id create_origin_id,\n\toem.create_type create_type,\n\toem.create_by create_by,\n\toem.create_time create_time,\n\toem.update_by update_by,\n\toem.update_time update_time,\n\tval.oem_partsku_value oem_partsku_value,\n\ttc.oem_partsku_code oem_partsku_code\nFROM \n(SELECT\n\toem_partsku_id,\n\tcarmodel_brand_id,\n\tstd_tree_id,\n\toem_partsku_desc,\n\toem_partsku_desc_img,\n\toem_partsku_status,\n\tcreate_origin,\n\tcreate_origin_id,\n\tcreate_type,\n\tcreate_by,\n\tcreate_time,\n\tupdate_by,\n\tupdate_time\nFROM \n\tscps_mysql_ods.t_oem_partsku final\nwhere ${oem_partsku_id} \n\tdata_flag > 0) oem\nGLOBAL\nLEFT JOIN (\n\tselect\n\t\toem_partsku_id,\n\t\tarrayStringConcat(groupArray(concat(toString(category_pro_id),\n\t\t':',\n\t\toem_partsku_value)),\n\t\t',') as oem_partsku_value\n\tFROM\n\t\tscps_mysql_ods.t_oem_partsku_value final\n\twhere ${oem_partsku_id} \n\t\tdata_flag > 0\n\tGROUP BY\n\t\toem_partsku_id) as val \n\t\t\ton\n\toem.oem_partsku_id = val.oem_partsku_id\nGLOBAL\nLEFT JOIN (\nSELECT\n\toem_partsku_id,\n\tconcat('[',arrayStringConcat(groupArray(concat('{\"oem_partsku_code\":\"',replaceAll(oem_partsku_code,'\"','\\\\\"'),'\",\"oem_partsku_fmt_code\":\"',\n\toem_partsku_fmt_code,'\",\"oem_partsku_code_index\":\"',toString(oem_partsku_code_index),'\"}')),','),']') oem_partsku_code\nFROM \n\tscps_mysql_ods.t_oem_partsku_code final\nwhere ${oem_partsku_id}\n\tdata_flag > 0\nGROUP BY\n\toem_partsku_id) as tc\n\tON \n\toem.oem_partsku_id = tc.oem_partsku_id";

    public static String oemImg = "select\n\ta.oem_partsku_id,\n\ta.oem_partsku_image_rel_index,\n\ta.oem_partsku_image_id,\n\ta.oem_partsku_image_type,\n\ta.category_pro_id,\n\tb.std_tree_id,\n\tb.oem_partsku_image_name,\n\tb.oem_partsku_image_url\nfrom\n\t(\n\tselect\n\t\toem_partsku_id,\n\t\toem_partsku_image_rel_index,\n\t\toem_partsku_image_id,\n\t\toem_partsku_image_type,\n\t\tcategory_pro_id\n\tfrom\n\t\tscps_mysql_ods.t_oem_partsku_image_rel final\n\twhere ${oem_partsku_id}\n\t\tdata_flag > 0) a\nGLOBAL\nJOIN (\n\tSELECT\n\t\toem_partsku_image_id,\n\t\tstd_tree_id,\n\t\toem_partsku_image_name,\n\t\toem_partsku_image_url\n\tfrom\n\t\tscps_mysql_ods.t_oem_partsku_image final\n\tWHERE\n\t\tdata_flag > 0\n) b on\n\ta.oem_partsku_image_id = b.oem_partsku_image_id";

}
