package com.flinkuse.cases.code.sql;

public class RealSql {

    public static String cmQuerySql = "SELECT\n\tcm_brand,\n\tcm_engine_model,\n\tgroup_concat(cast(cm_id as varchar)) cm_ids\nFROM\n\tscps_mysql_ods.t_carmodel_base\nWHERE\n\tcm_brand in (%s)\n\tand cm_engine_model in (%s)\n\tand data_flag > 0\nGROUP BY\n\tcm_brand,\n\tcm_engine_model";

    public static String productSql = "select dealer_partsku_id\n,dealer_partsku_code\n,dealer_partsku_external_code\n,dealer_partsku_order_url\n,tenant_id\n,ten_sys_id\n,dealer_category_id\n,dealer_part_id\n,agent_tenant_id\n,agent_ten_brand_id\n,agent_ten_category_id\n,agent_ten_part_id\n,agent_ten_partsku_code\n,category_id from \nscps_mysql_ods.t_dealer_partsku\nwhere dealer_partsku_id in (${dealer_partsku_id}) and data_flag > 0";

    public static String fmsSql = "select a.fms_partsku_id\n,a.fms_partsku_desc\n,a.fms_partsku_desc_img\n,a.fms_partsku_status\n,a.category_id\n,a.fms_brand_id\n,a.fms_category_id\n,b.fms_partsku_code_id\n,b.fms_partsku_code\n,b.fms_partsku_fmt_code\nfrom ( select fms_partsku_id\n,fms_partsku_desc\n,fms_partsku_desc_img\n,fms_partsku_status\n,category_id\n,fms_brand_id\n,fms_category_id\nfrom scps_mysql_ods.t_famous_partsku where fms_partsku_id in (${fms_partsku_id}) and data_flag > 0)a\n left join \n(select fms_partsku_id,fms_partsku_code_id,fms_partsku_code,fms_partsku_fmt_code\nfrom scps_mysql_ods.t_famous_partsku_code where fms_partsku_id in (${fms_partsku_id}) and data_flag > 0 )b \non a.fms_partsku_id = b.fms_partsku_id \n";

    public static String insSql = "select a.indus_partsku_id\n,a.indus_partsku_desc\n,a.indus_partsku_desc_img\n,a.indus_partsku_status\n,a.category_id\n,a.indus_brand_id\n,a.indus_category_id\n,b.indus_partsku_code_id \n,b.indus_partsku_code \n,b.indus_partsku_fmt_code \nfrom (select indus_partsku_id,indus_partsku_desc,indus_partsku_desc_img,indus_partsku_status,category_id,indus_brand_id,indus_category_id from scps_mysql_ods.t_industry_partsku \n where indus_partsku_id in (${indus_partsku_id}) and data_flag > 0) a\n  left join\n (select indus_partsku_id,indus_partsku_code_id,indus_partsku_code,indus_partsku_fmt_code from scps_mysql_ods.t_industry_partsku_code\n where indus_partsku_id in (${indus_partsku_id}) and data_flag > 0) b \non a.indus_partsku_id = b.indus_partsku_id ";

    public static String oemSql = "select a.oem_partsku_id\n,a.carmodel_brand_id \n,a.std_tree_id \n,a.oem_partsku_desc \n,a.oem_partsku_desc_img \n,a.oem_partsku_status \n,a.create_origin \n,a.create_origin_id \n,a.create_type \n,b.oem_partsku_code_id \n,b.oem_partsku_code \n,b.oem_partsku_fmt_code \nfrom (select oem_partsku_id,carmodel_brand_id,std_tree_id,oem_partsku_desc,oem_partsku_desc_img,oem_partsku_status,create_origin,create_origin_id,create_type\nfrom scps_mysql_ods.t_oem_partsku \nwhere oem_partsku_id in (${oem_partsku_id}) and data_flag > 0) a \n left join\n(select oem_partsku_id,oem_partsku_code_id,oem_partsku_code,oem_partsku_fmt_code\nfrom scps_mysql_ods.t_oem_partsku_code \nwhere oem_partsku_id in (${oem_partsku_id}) and data_flag > 0) b on a.oem_partsku_id = b.oem_partsku_id ";

    public static String dealerSql = "select\na.prod_sku_id\n,a.prod_group_id\n,a.prod_sku_name\n,a.prod_sku_code\n,a.dealer_partsku_id\n,a.prod_sku_desc\n,a.prod_sku_desc_img\n,a.prod_sku_origin_price\n,a.prod_sku_stock\n,a.prod_sku_spec\n,a.prod_spu_id,a.prod_sku_brand_name,a.ten_partsku_code\n,a.prod_sku_weight\n,a.prod_sku_volume\n,a.prod_unit_id\n,a.prod_sku_status\n,a.prod_sku_min_purchase\n,b.dealer_partsku_code\n,b.dealer_partsku_external_code\n,b.dealer_partsku_order_url\n,b.tenant_id\n,a.ten_sys_id\n,b.dealer_category_id\n,b.dealer_part_id\n,b.agent_tenant_id\n,b.agent_ten_brand_id\n,b.agent_ten_category_id\n,b.agent_ten_part_id\n,b.agent_ten_partsku_code\n,a.category_id\n,rel.ten_brand_id\n,rel.ten_part_id\n,rel.ten_partsku_id \nfrom (select prod_sku_id\n,prod_spu_id,prod_sku_brand_name,ten_partsku_code\n,prod_group_id\n,prod_sku_name\n,prod_sku_code\n,dealer_partsku_id\n,prod_sku_desc\n,prod_sku_desc_img\n,prod_sku_origin_price\n,prod_sku_stock\n,prod_sku_spec\n,prod_sku_weight\n,prod_sku_volume\n,prod_unit_id\n,prod_sku_status\n,prod_sku_min_purchase,ten_sys_id,category_id \nfrom scps_mysql_ods.t_product_sku\n where prod_sku_id in (${prod_sku_id}) and data_flag > 0) a\n  left join\n (select dealer_partsku_id\n,dealer_partsku_code\n,dealer_partsku_external_code\n,dealer_partsku_order_url\n,tenant_id\n,ten_sys_id\n,dealer_category_id\n,dealer_part_id\n,agent_tenant_id\n,agent_ten_brand_id\n,agent_ten_category_id\n,agent_ten_part_id\n,agent_ten_partsku_code\n,category_id from scps_mysql_ods.t_dealer_partsku\nwhere dealer_partsku_id in (SELECT dealer_partsku_id FROM  scps_mysql_ods.t_product_sku WHERE prod_sku_id in (${prod_sku_id})) and data_flag > 0) b \non a.dealer_partsku_id = b.dealer_partsku_id \n left join\n(select prod_sku_id,ten_brand_id,ten_part_id,ten_partsku_id from scps_mysql_ods.t_product_tenant_rel WHERE prod_sku_id in (${prod_sku_id}) AND data_flag > 0) rel on \na.prod_sku_id = rel.prod_sku_id ";

    public static String dpSql = "select\n\ta.prod_sku_id,\n\ta.prod_group_id,\n\ta.prod_sku_name,\n\ta.prod_sku_code,\n\ta.dealer_partsku_id,\n\ta.prod_sku_desc,\n\ta.prod_sku_desc_img,\n\ta.prod_sku_origin_price,\n\ta.prod_sku_stock,\n\ta.prod_sku_spec,\n\ta.prod_spu_id,\n\ta.prod_sku_brand_name,\n\ta.ten_partsku_code,\n\ta.prod_sku_weight,\n\ta.prod_sku_volume,\n\ta.prod_unit_id,\n\ta.prod_sku_status,\n\ta.prod_sku_min_purchase,\n\tb.dealer_partsku_code,\n\tb.dealer_partsku_external_code,\n\tb.dealer_partsku_order_url,\n\tb.tenant_id,\n\ta.ten_sys_id,\n\tb.dealer_category_id,\n\tb.dealer_part_id,\n\tb.agent_tenant_id,\n\tb.agent_ten_brand_id,\n\tb.agent_ten_category_id,\n\tb.agent_ten_part_id,\n\tb.agent_ten_partsku_code,\n\ta.category_id,\n\trel.ten_brand_id,\n\trel.ten_part_id,\n\trel.ten_partsku_id\nfrom\n\t(\n\tselect\n\t\tprod_sku_id,\n\t\tprod_spu_id,\n\t\tprod_sku_brand_name,\n\t\tten_partsku_code,\n\t\tprod_group_id,\n\t\tprod_sku_name,\n\t\tprod_sku_code,\n\t\tdealer_partsku_id,\n\t\tprod_sku_desc,\n\t\tprod_sku_desc_img,\n\t\tprod_sku_origin_price,\n\t\tprod_sku_stock,\n\t\tprod_sku_spec,\n\t\tprod_sku_weight,\n\t\tprod_sku_volume,\n\t\tprod_unit_id,\n\t\tprod_sku_status,\n\t\tprod_sku_min_purchase,\n\t\tten_sys_id,\n\t\tcategory_id\n\tfrom\n\t\tscps_mysql_ods.t_product_sku\n\twhere\n\t\tdealer_partsku_id in (${dealer_partsku_id})\n\t\tand data_flag > 0) a\nleft join\n (\n\tselect\n\t\tdealer_partsku_id,\n\t\tdealer_partsku_code,\n\t\tdealer_partsku_external_code,\n\t\tdealer_partsku_order_url,\n\t\ttenant_id,\n\t\tten_sys_id,\n\t\tdealer_category_id,\n\t\tdealer_part_id,\n\t\tagent_tenant_id,\n\t\tagent_ten_brand_id,\n\t\tagent_ten_category_id,\n\t\tagent_ten_part_id,\n\t\tagent_ten_partsku_code,\n\t\tcategory_id\n\tfrom\n\t\tscps_mysql_ods.t_dealer_partsku\n\twhere\n\t\tdealer_partsku_id in (${dealer_partsku_id})\n\t\tand data_flag > 0) b \non\n\ta.dealer_partsku_id = b.dealer_partsku_id\nleft join\n(\n\tselect\n\t\tprod_sku_id,\n\t\tten_brand_id,\n\t\tten_part_id,\n\t\tten_partsku_id\n\tfrom\n\t\tscps_mysql_ods.t_product_tenant_rel\n\tWHERE\n\t\tprod_sku_id in (select prod_sku_id from scps_mysql_ods.t_product_sku WHERE dealer_partsku_id in (${dealer_partsku_id}) and data_flag > 0)\n\t\t\tAND data_flag > 0) rel on\n\ta.prod_sku_id = rel.prod_sku_id";

    public static String skuSql = "SELECT ten_partsku_id,\nten_partsku_code,\nten_partsku_external_code,\nten_partsku_feature,\nten_partsku_order_url,\nten_partsku_course_url,\ntenant_id,\nten_brand_id,\nten_category_id,\nten_part_id,\nten_partsku_desc,\nten_partsku_desc_img,\ncategory_id  from scps_mysql_ods.t_tenant_partsku\nwhere ten_partsku_id in (${ten_partsku_id}) and data_flag > 0";

    public static String exchangeSql = "select partsku_exchange_id,\npartsku_exchange_brand_id,\npartsku_exchange_code,\npartsku_exchange_fmt_code,\npartsku_exchange_type,\ntenant_id,\nten_brand_id,\nten_category_id,\nten_part_id,\nten_partsku_id,\ncategory_id from scps_mysql_ods.t_tenant_partsku_exchange \nwhere partsku_exchange_id in (${partsku_exchange_id}) and data_flag > 0";

    public static String ch_cmQuerySql = "SELECT\n\tcm_brand,\n\tcm_engine_model,\n\tarrayStringConcat(groupUniqArray(toString(cm_id)),',') cm_ids\nFROM\n\tscps_mysql_ods.t_carmodel_base final\nWHERE\n\tcm_brand GLOBAL in (%s)\n\tand cm_engine_model GLOBAL in (%s)\n\tand data_flag > 0\nGROUP BY\n\tcm_brand,\n\tcm_engine_model";

    public static String ch_productSql = "select dealer_partsku_id\n,dealer_partsku_code\n,dealer_partsku_external_code\n,dealer_partsku_order_url\n,tenant_id\n,dealer_category_id\n,dealer_part_id\n,agent_tenant_id\n,agent_ten_brand_id\n,agent_ten_category_id\n,agent_ten_part_id\n,agent_ten_partsku_code\n,category_id from \nscps_mysql_ods.t_dealer_partsku final\nwhere dealer_partsku_id GLOBAL in (${dealer_partsku_id}) and data_flag > 0";

    public static String ch_fmsSql = "select a.fms_partsku_id\n,a.fms_partsku_desc\n,a.fms_partsku_desc_img\n,a.fms_partsku_status\n,a.category_id\n,a.fms_brand_id\n,a.fms_category_id\n,b.fms_partsku_code_id\n,b.fms_partsku_code\n,b.fms_partsku_fmt_code\nfrom ( select fms_partsku_id\n,fms_partsku_desc\n,fms_partsku_desc_img\n,fms_partsku_status\n,category_id\n,fms_brand_id\n,fms_category_id\nfrom scps_mysql_ods.t_famous_partsku final where fms_partsku_id GLOBAL in (${fms_partsku_id}) and data_flag > 0)a\n left join \n(select fms_partsku_id,fms_partsku_code_id,fms_partsku_code,fms_partsku_fmt_code \nfrom scps_mysql_ods.t_famous_partsku_code final where fms_partsku_id GLOBAL in (${fms_partsku_id}) and data_flag > 0 )b \non a.fms_partsku_id = b.fms_partsku_id ";

    public static String ch_insSql = "select a.indus_partsku_id\n,a.indus_partsku_desc\n,a.indus_partsku_desc_img\n,a.indus_partsku_status\n,a.category_id\n,a.indus_brand_id\n,a.indus_category_id\n,b.indus_partsku_code_id \n,b.indus_partsku_code \n,b.indus_partsku_fmt_code \nfrom (select indus_partsku_id,indus_partsku_desc,indus_partsku_desc_img,indus_partsku_status,category_id,indus_brand_id,indus_category_id from scps_mysql_ods.t_industry_partsku final\n where indus_partsku_id GLOBAL in (${indus_partsku_id}) and data_flag > 0) a\n  left join\n (select indus_partsku_id,indus_partsku_code_id,indus_partsku_code,indus_partsku_fmt_code from scps_mysql_ods.t_industry_partsku_code final\n where indus_partsku_id GLOBAL in (${indus_partsku_id}) and data_flag > 0) b \non a.indus_partsku_id = b.indus_partsku_id ";

    public static String ch_oemSql = "select a.oem_partsku_id\n,a.carmodel_brand_id \n,a.std_tree_id \n,a.oem_partsku_desc \n,a.oem_partsku_desc_img \n,a.oem_partsku_status \n,a.create_origin \n,a.create_origin_id \n,a.create_type \n,b.oem_partsku_code_id \n,b.oem_partsku_code \n,b.oem_partsku_fmt_code \nfrom (select oem_partsku_id,carmodel_brand_id,std_tree_id,oem_partsku_desc,oem_partsku_desc_img,oem_partsku_status,create_origin,create_origin_id,create_type\nfrom scps_mysql_ods.t_oem_partsku final\nwhere oem_partsku_id GLOBAL in (${oem_partsku_id}) and data_flag > 0) a \n left join\n(select oem_partsku_id,oem_partsku_code_id,oem_partsku_code,oem_partsku_fmt_code\nfrom scps_mysql_ods.t_oem_partsku_code final \nwhere oem_partsku_id GLOBAL in (${oem_partsku_id}) and data_flag > 0) b on a.oem_partsku_id = b.oem_partsku_id ";

    public static String ch_dealerSql = "select\na.prod_sku_id\n,a.prod_group_id\n,a.prod_sku_name\n,a.prod_sku_code\n,a.dealer_partsku_id\n,a.prod_sku_desc\n,a.prod_sku_desc_img\n,a.prod_sku_origin_price\n,a.prod_sku_stock\n,a.prod_sku_spec\n,a.prod_spu_id,a.prod_sku_brand_name,a.ten_partsku_code\n,a.prod_sku_weight\n,a.prod_sku_volume\n,a.prod_unit_id\n,a.prod_sku_status\n,a.prod_sku_min_purchase\n,b.dealer_partsku_code\n,b.dealer_partsku_external_code\n,b.dealer_partsku_order_url\n,b.tenant_id\n,a.ten_sys_id\n,b.dealer_category_id\n,b.dealer_part_id\n,b.agent_tenant_id\n,b.agent_ten_brand_id\n,b.agent_ten_category_id\n,b.agent_ten_part_id\n,b.agent_ten_partsku_code\n,a.category_id\n,rel.ten_brand_id\n,rel.ten_part_id\n,rel.ten_partsku_id \nfrom (select prod_sku_id\n,prod_spu_id,prod_sku_brand_name,ten_partsku_code\n,prod_group_id\n,prod_sku_name\n,prod_sku_code\n,dealer_partsku_id\n,prod_sku_desc\n,prod_sku_desc_img\n,prod_sku_origin_price\n,prod_sku_stock\n,prod_sku_spec\n,prod_sku_weight\n,prod_sku_volume\n,prod_unit_id\n,prod_sku_status\n,prod_sku_min_purchase,ten_sys_id,category_id \nfrom scps_mysql_ods.t_product_sku final\n where prod_sku_id in (${prod_sku_id}) and data_flag > 0) a\n  left join\n (select dealer_partsku_id\n,dealer_partsku_code\n,dealer_partsku_external_code\n,dealer_partsku_order_url\n,tenant_id\n,dealer_category_id\n,dealer_part_id\n,agent_tenant_id\n,agent_ten_brand_id\n,agent_ten_category_id\n,agent_ten_part_id\n,agent_ten_partsku_code\n,category_id from scps_mysql_ods.t_dealer_partsku final\nwhere dealer_partsku_id GLOBAL in (SELECT dealer_partsku_id FROM  scps_mysql_ods.t_product_sku final WHERE prod_sku_id GLOBAL in (${prod_sku_id})) and data_flag > 0) b \non a.dealer_partsku_id = b.dealer_partsku_id \n left join\n(select prod_sku_id,ten_brand_id,ten_part_id,ten_partsku_id from scps_mysql_ods.t_product_tenant_rel final WHERE prod_sku_id GLOBAL in (${prod_sku_id}) AND data_flag > 0) rel on \na.prod_sku_id = rel.prod_sku_id";

    public static String ch_dpSql = "select\n\ta.prod_sku_id,\n\ta.prod_group_id,\n\ta.prod_sku_name,\n\ta.prod_sku_code,\n\ta.dealer_partsku_id,\n\ta.prod_sku_desc,\n\ta.prod_sku_desc_img,\n\ta.prod_sku_origin_price,\n\ta.prod_sku_stock,\n\ta.prod_sku_spec,\n\ta.prod_spu_id,\n\ta.prod_sku_brand_name,\n\ta.ten_partsku_code,\n\ta.prod_sku_weight,\n\ta.prod_sku_volume,\n\ta.prod_unit_id,\n\ta.prod_sku_status,\n\ta.prod_sku_min_purchase,\n\tb.dealer_partsku_code,\n\tb.dealer_partsku_external_code,\n\tb.dealer_partsku_order_url,\n\tb.tenant_id,\n\ta.ten_sys_id,\n\tb.dealer_category_id,\n\tb.dealer_part_id,\n\tb.agent_tenant_id,\n\tb.agent_ten_brand_id,\n\tb.agent_ten_category_id,\n\tb.agent_ten_part_id,\n\tb.agent_ten_partsku_code,\n\ta.category_id,\n\trel.ten_brand_id,\n\trel.ten_part_id,\n\trel.ten_partsku_id\nfrom\n\t(\n\tselect\n\t\tprod_sku_id,\n\t\tprod_spu_id,\n\t\tprod_sku_brand_name,\n\t\tten_partsku_code,\n\t\tprod_group_id,\n\t\tprod_sku_name,\n\t\tprod_sku_code,\n\t\tdealer_partsku_id,\n\t\tprod_sku_desc,\n\t\tprod_sku_desc_img,\n\t\tprod_sku_origin_price,\n\t\tprod_sku_stock,\n\t\tprod_sku_spec,\n\t\tprod_sku_weight,\n\t\tprod_sku_volume,\n\t\tprod_unit_id,\n\t\tprod_sku_status,\n\t\tprod_sku_min_purchase,\n\t\tten_sys_id,\n\t\tcategory_id\n\tfrom\n\t\tscps_mysql_ods.t_product_sku final\n\twhere\n\t\tdealer_partsku_id GLOBAL in (${dealer_partsku_id})\n\t\tand data_flag > 0) a\nleft join\n (\n\tselect\n\t\tdealer_partsku_id,\n\t\tdealer_partsku_code,\n\t\tdealer_partsku_external_code,\n\t\tdealer_partsku_order_url,\n\t\ttenant_id,\n\t\tten_sys_id,\n\t\tdealer_category_id,\n\t\tdealer_part_id,\n\t\tagent_tenant_id,\n\t\tagent_ten_brand_id,\n\t\tagent_ten_category_id,\n\t\tagent_ten_part_id,\n\t\tagent_ten_partsku_code,\n\t\tcategory_id\n\tfrom\n\t\tscps_mysql_ods.t_dealer_partsku final\n\twhere\n\t\tdealer_partsku_id GLOBAL in (${dealer_partsku_id})\n\t\tand data_flag > 0) b \non\n\ta.dealer_partsku_id = b.dealer_partsku_id\nleft join\n(\n\tselect\n\t\tprod_sku_id,\n\t\tten_brand_id,\n\t\tten_part_id,\n\t\tten_partsku_id\n\tfrom\n\t\tscps_mysql_ods.t_product_tenant_rel final\n\tWHERE\n\t\tprod_sku_id GLOBAL in (select prod_sku_id from scps_mysql_ods.t_product_sku WHERE dealer_partsku_id GLOBAL in (${dealer_partsku_id}) and data_flag > 0)\n\t\t\tAND data_flag > 0) rel on\n\ta.prod_sku_id = rel.prod_sku_id";

    public static String ch_skuSql = "SELECT ten_partsku_id,\nten_partsku_code,\nten_partsku_external_code,\nten_partsku_feature,\nten_partsku_order_url,\nten_partsku_course_url,\ntenant_id,\nten_brand_id,\nten_category_id,\nten_part_id,\nten_partsku_desc,\nten_partsku_desc_img,\ncategory_id  from scps_mysql_ods.t_tenant_partsku final\nwhere ten_partsku_id GLOBAL in (${ten_partsku_id}) and data_flag > 0";

    public static String ch_exchangeSql = "select partsku_exchange_id,\npartsku_exchange_brand_id,\npartsku_exchange_code,\npartsku_exchange_fmt_code,\npartsku_exchange_type,\ntenant_id,\nten_brand_id,\nten_category_id,\nten_part_id,\nten_partsku_id,\ncategory_id from scps_mysql_ods.t_tenant_partsku_exchange final\nwhere partsku_exchange_id GLOBAL in (${partsku_exchange_id}) and data_flag > 0";

}

